---
title: "First Knit"
author: "Carmen Ramos-Caminos"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer    
I attended Saint Monica Catholic High School in Santa Monica Ca. I graduated in 1989. English was a much easier subject for me in high school. Ironically, I am a para educator in a middle school math classroom. 

## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
At home i have access to an Apple desktop computer. It can be pretty finicky. I also have access to a Google chrome book. On a scale from 1-10 on computer saveyness I believe I am a 5. Computers and computer programs frighten me. I do not usually give up, but today has been a bit overwhelming. I have spectrum internet at home and service is usually pretty good at home. 
   
## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
 My name is Carmen. I am fine with being called Carmen. My family calls me Ile (ILL-EE) that's short for Ileana my middle name. I have been called random names like Karmine, Carmina, Carmencita, Carmenza, Karmon, Arman and Kermit???
 
## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
  My goal is to become an early childhood educator. I currently work at a local middle school, but that is not where I want to finish. I enjoy being the adult that will teach children the foundations needed to develop a passion for learning. I want to build positive relationships with young students so that they love being in school. 


## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 I have never been to any other foreign countries other than Mexico. It is my goal and on my bucket list to visit Iceland in my lifetime. I do have a life savings that i have been saving for this trip of a lifetime. 

## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 
### my answer     
  
Statistics is my final class to complete and AA in Early Childhood Education and an AA in Administration Justice. This class has been haunting me for years. The first time I took it I had to drop it because my father was hospitalized after a heart attack and my family needed me. I took it again in 2021, but I made a choice to drop it because i was offered a job where I work now, and I could not pass up the opportunity to have in-class experience. I am taking it again, but unfortunately my father passed away  May 12,2022 and I m under alot of pressure. Im going to do my best to stick to this and pass this class because I cannot give up now.    
 






  




